sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t shreyp08/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true shreyp08/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: ap-south-1
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-627919072036"
  bucket_path: "docker-react" #default_path == app name
  on:
    branch: master #Only auto-deploy if code is pushed to master
  access_key_id: $AccessKeyID
  secret_access_key: "$SecretAccessKey"
