FROM node:18-alpine

USER node

RUN mkdir -p /home/node/app
WORKDIR '/home/node/app'

COPY --chown=node:node ./package.json ./
RUN npm install

## Already copying files in docker-compose.yaml. Leaving this here for reference.
# COPY <FROM> <TO>
COPY --chown=node:node ./ ./ 

CMD ["npm", "run", "start"]